# -*- coding: utf-8 -*-
"""deney2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBGF7VqVWtiFIzW4oF-AL21BPl7hmyCd
"""

!pip install -q mediapipe timm opencv-python-headless
!pip install -q --no-cache-dir "protobuf==5.29.3"

!wget -q -O face_landmarker.task https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task

import os
print(os.path.exists("/usr/local/lib/python3.12/dist-packages/google/protobuf/runtime_version.py"))
!pip show protobuf | grep Version

!pip install -q --no-deps --force-reinstall mediapipe

import os, cv2, random, time, json, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from pathlib import Path
from PIL import Image
from tqdm.notebook import tqdm

import torch
import torch.nn as nn
import torchvision.transforms as T
import torchvision.models as models
from torch.utils.data import Dataset, DataLoader

import timm
import mediapipe as mp

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, average_precision_score,
    confusion_matrix, roc_curve, precision_recall_curve
)

warnings.filterwarnings("ignore")

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Cihaz: {DEVICE}")
print(f"✅ PyTorch: {torch.__version__}")
print(f"✅ Timm: {timm.__version__}")

# ═══════════════════════════════════════════════════════════════
# 📥 KAGGLE'DAN DOĞRUDAN İNDİRME (Drive İşkencesine Son)
# ═══════════════════════════════════════════════════════════════
!pip install -q kagglehub
import kagglehub
import os

# Aşağıdaki tırnak içlerine Kaggle bilgilerini gir:
os.environ["KAGGLE_USERNAME"] = "KaderTerik"
os.environ["KAGGLE_KEY"]      = "KGAT_b40352971e4e5e85cb64cdede6a834ef"

print("🚀 Kaggle'dan indiriliyor (Çok hızlıdır, bekle)...")
# ff-c23 datasetini direkt Colab'ın hafızasına indirir
dataset_path = kagglehub.dataset_download("xdxd003/ff-c23")

print(f"\n✅ İndirme tamamlandı! Dataset Colab'a indi: {dataset_path}")

BASE_DIR = os.path.join(dataset_path, "FaceForensics++_C23")

# ═══════════════════════════════════════════════════════════════
# ⚙️ SABİT KONFİGÜRASYON (Hafızaya Yeniden Alma)
# ═══════════════════════════════════════════════════════════════

import os, random
import numpy as np
import torch

BASE_DIR = "/root/.cache/kagglehub/datasets/xdxd003/ff-c23/versions/1/FaceForensics++_C23"

CONFIG = {
    # --- Dataset ---
    "real_dir":       [os.path.join(BASE_DIR, "original")],
    "fake_dir":       [
        os.path.join(BASE_DIR, "DeepFakeDetection"),
        os.path.join(BASE_DIR, "Deepfakes"),
        os.path.join(BASE_DIR, "Face2Face"),
        os.path.join(BASE_DIR, "FaceShifter"),
        os.path.join(BASE_DIR, "FaceSwap"),
        os.path.join(BASE_DIR, "NeuralTextures")
    ],

    "output_dir":     "/content/eye_dataset",
    "results_dir":    "/content/results",
    "reports_dir":    "/content/reports",

    # --- Ayarlar ---
    "frames_per_video": 20,
    "video_ext":        [".mp4", ".avi"],
    "image_size":     128,
    "padding":        0.25,
    "train_ratio":    0.70,
    "val_ratio":      0.15,
    "test_ratio":     0.15,

    "seed":           42,
    "epochs":         10,
    "batch_size":     32,
    "learning_rate":  0.0001,
    "optimizer":      "Adam",
    "loss":           "CrossEntropyLoss",
    "save_metric":    "roc_auc",
    "current_model":  "resnet18",
}

EXPERIMENTS = {
    "EXP001": "resnet18",
    "EXP002": "efficientnet_b0",
    "EXP003": "densenet121",
    "EXP004": "mobilenet_v3_small",
    "EXP005": "xception",
}

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(CONFIG["seed"])

for d in [CONFIG["output_dir"], CONFIG["results_dir"], CONFIG["reports_dir"]]:
    os.makedirs(d, exist_ok=True)

# 🚨 ÇOK ÖNEMLİ: Hücre 4'ü atlayacağımız için raw_frames yolunu manuel belirtiyoruz
CONFIG["raw_frames_dir"] = CONFIG["output_dir"] + "/raw_frames"

print("✅ Config Başarıyla Yüklendi! Hücre 4'ü ATLA, direkt Hücre 5'e geç!")

# ═══════════════════════════════════════════════════════════════
# 🎬 FRAME EXTRACTION — cap.set() Olmadan Süper Hızlı Okuma
# ═══════════════════════════════════════════════════════════════

import cv2, os, random
import numpy as np
from pathlib import Path
from tqdm.notebook import tqdm

def extract_frames_from_video(video_path, output_dir, video_id, label, n_frames=20):
    cap = cv2.VideoCapture(str(video_path))
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total <= 0: return 0

    if total < n_frames:
        indices = set(range(total))
    else:
        indices = set(np.linspace(0, total - 1, n_frames, dtype=int))

    saved = 0
    current_frame = 0

    # cap.set() YERİNE DÜZ OKUMA (Yüzlerce kat daha hızlı)
    while True:
        ret, frame = cap.read()
        if not ret: break  # Video bitti

        if current_frame in indices:
            fname = f"{label}_{video_id}_{current_frame:05d}.jpg"
            cv2.imwrite(os.path.join(output_dir, fname), frame)
            saved += 1

        current_frame += 1
        # Tüm istediğimiz kareleri aldıysak videonun kalanını okumaya gerek yok
        if saved >= n_frames: break

    cap.release()
    return saved

def get_video_files(directories, extensions):
    videos = []
    if isinstance(directories, str): directories = [directories]
    for d in directories:
        for ext in extensions:
            videos.extend(Path(d).rglob(f"*{ext}"))
    return sorted(videos)

def video_level_split(video_list, train_r=0.70, val_r=0.15, seed=42, max_limit=500):
    random.seed(seed)
    vids = list(video_list)
    random.shuffle(vids)
    if len(vids) > max_limit: vids = vids[:max_limit]
    n = len(vids)
    t = int(n * train_r)
    v = int(n * val_r)
    return vids[:t], vids[t:t+v], vids[t+v:]

def run_fast_extraction():
    raw_dir  = CONFIG["output_dir"] + "/raw_frames"

    for split in ["train", "val", "test"]:
        for label in ["real", "fake"]:
            os.makedirs(f"{raw_dir}/{split}/{label}", exist_ok=True)

    print("🔍 Dosyalar taranıyor...")
    real_videos = get_video_files(CONFIG["real_dir"], CONFIG["video_ext"])
    fake_videos = get_video_files(CONFIG["fake_dir"], CONFIG["video_ext"])

    r_train, r_val, r_test = video_level_split(real_videos, CONFIG["train_ratio"], CONFIG["val_ratio"], CONFIG["seed"], max_limit=500)
    f_train, f_val, f_test = video_level_split(fake_videos, CONFIG["train_ratio"], CONFIG["val_ratio"], CONFIG["seed"], max_limit=500)

    splits = {
        "train": (r_train, f_train),
        "val":   (r_val,   f_val),
        "test":  (r_test,  f_test),
    }

    print(f"🚀 Süper Hızlı Mod devrede... (Toplam 1000 Video)")

    total_frames = 0
    for split_name, (reals, fakes) in splits.items():
        for label, vids in [("real", reals), ("fake", fakes)]:
            out = f"{raw_dir}/{split_name}/{label}"
            for i, vpath in enumerate(tqdm(vids, desc=f"{label} ({split_name})")):
                n = extract_frames_from_video(vpath, out, video_id=i, label=label, n_frames=CONFIG["frames_per_video"])
                total_frames += n

    print(f"\n✅ FİŞEK GİBİ BİTTİ! Çıkarılan Kare: {total_frames}")
    CONFIG["raw_frames_dir"] = raw_dir
    return raw_dir

raw_frames_dir = run_fast_extraction()

# ═══════════════════════════════════════════════════════════════
# 👁️ EYE REGION EXTRACTION — MediaPipe Tasks API (Yeni Nesil)
# ═══════════════════════════════════════════════════════════════

# 1. Gerekli model dosyasını Google'dan indir (Sadece 1 saniye sürer)
!wget -q -O face_landmarker.task https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task

import cv2, os
import mediapipe as mp
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision as mp_vision
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pathlib import Path
from tqdm.notebook import tqdm

# MediaPipe Göz Landmark İndeksleri
LEFT_EYE  = [33, 7, 163, 144, 145, 153, 154, 155, 133, 173, 157, 158, 159, 160, 161, 246]
RIGHT_EYE = [362, 382, 381, 380, 374, 373, 390, 249, 263, 466, 388, 387, 386, 385, 384, 398]

# Detector'ü BİR KERE oluştur (performans için)
base_options = mp_python.BaseOptions(model_asset_path='face_landmarker.task')
options = mp_vision.FaceLandmarkerOptions(base_options=base_options, num_faces=1)
face_landmarker = mp_vision.FaceLandmarker.create_from_options(options)

def get_eye_bbox(landmarks, eye_indices, img_w, img_h, padding=0.25):
    xs = [landmarks[i].x * img_w for i in eye_indices]
    ys = [landmarks[i].y * img_h for i in eye_indices]
    x1, x2 = int(min(xs)), int(max(xs))
    y1, y2 = int(min(ys)), int(max(ys))
    pw = int((x2 - x1) * padding)
    ph = int((y2 - y1) * padding)
    return max(0, x1 - pw), max(0, y1 - ph), min(img_w, x2 + pw), min(img_h, y2 + ph)

def extract_eye_region(image_path, size=128, padding=0.25):
    img = cv2.imread(str(image_path))
    if img is None: return None

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w = img.shape[:2]

    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)
    result = face_landmarker.detect(mp_image)

    if not result.face_landmarks: return None  # Yüz bulunamadı

    lm = result.face_landmarks[0]

    lx1, ly1, lx2, ly2 = get_eye_bbox(lm, LEFT_EYE, w, h, padding)
    rx1, ry1, rx2, ry2 = get_eye_bbox(lm, RIGHT_EYE, w, h, padding)

    left_eye  = img_rgb[ly1:ly2, lx1:lx2]
    right_eye = img_rgb[ry1:ry2, rx1:rx2]

    if left_eye.size == 0 or right_eye.size == 0: return None

    half = size // 2
    left_eye  = cv2.resize(left_eye, (half, size))
    right_eye = cv2.resize(right_eye, (half, size))
    combined  = np.concatenate([left_eye, right_eye], axis=1)

    return Image.fromarray(combined)

def run_eye_extraction():
    raw_dir = CONFIG["raw_frames_dir"]
    eye_dir = CONFIG["output_dir"] + "/eye_regions"
    skipped, processed = 0, 0

    print("✂️ Göz Kesme İşlemi Başlıyor...")
    for split in ["train", "val", "test"]:
        for label in ["real", "fake"]:
            src = Path(f"{raw_dir}/{split}/{label}")
            dst = Path(f"{eye_dir}/{split}/{label}")
            dst.mkdir(parents=True, exist_ok=True)

            frames = list(src.glob("*.jpg"))
            for fpath in tqdm(frames, desc=f"{split.upper()} - {label.upper()}"):
                eye_img = extract_eye_region(fpath, size=CONFIG["image_size"], padding=CONFIG["padding"])
                if eye_img is None:
                    skipped += 1
                    continue
                eye_img.save(dst / fpath.name)
                processed += 1

    total = processed + skipped
    rate = 100 * processed / total if total > 0 else 0
    print(f"\n✅ GÖZ KESME BİTTİ!")
    print(f"👁️ Çıkarılan Göz: {processed}")
    print(f"❌ Yüz Bulunamayan: {skipped} (Atlandı)")
    print(f"🎯 Başarı Oranı: %{rate:.1f}")
    CONFIG["eye_dir"] = eye_dir
    return eye_dir

# 1. ÇALIŞTIRMA
eye_dir = run_eye_extraction()

# 2. ÖRNEK GÖRSELLERİ EKRANA BASTIR (Jüri Şovu)
print("\n🖼️ ÖRNEK GÖZ GÖRÜNTÜLERİ (Model Bunları Öğrenecek):")
fig, axes = plt.subplots(2, 4, figsize=(12, 6))
fig.suptitle("MediaPipe Tarafından Çıkarılan Göz Bölgeleri (128x128)", fontsize=14, fontweight='bold')
for row, label in enumerate(["real", "fake"]):
    samples = list(Path(f"{eye_dir}/train/{label}").glob("*.jpg"))[:4]
    for col, p in enumerate(samples):
        if not samples: continue
        axes[row, col].imshow(Image.open(p))
        axes[row, col].set_title(label.upper(), color="green" if label=="real" else "red")
        axes[row, col].axis("off")
plt.tight_layout()
plt.show()

# ═══════════════════════════════════════════════════════════════
# 💾 EMEKLERİ GÜVENCEYE ALMA (Drive'a Yedekleme)
# ═══════════════════════════════════════════════════════════════

import shutil
import os

backup_path = "/content/drive/MyDrive/eye_dataset_backup"
print("📦 Göz fotoğrafları ZİPLENİYOR ve Drive'a atılıyor... Lütfen bekleyin...")

# Sadece gözlerin olduğu klasörü zipleyip Drive'a kaydeder
shutil.make_archive(backup_path, 'zip', CONFIG["eye_dir"])

print(f"✅ BÜTÜN EMEKLERİN GÜVENDE! Veri seti şuraya kaydedildi: {backup_path}.zip")
print("😴 Artık bilgisayarını açık bırakıp rahatça uyuyabilirsin. Colab kapansa bile yarın doğrudan eğitimden devam edeceğiz!")

CONFIG["mean"] = [0.485, 0.456, 0.406]
CONFIG["std"] = [0.229, 0.224, 0.225]

# ═══════════════════════════════════════════════════════════════
# 🧠 VERİ YÜKLEYİCİ (Dataset & DataLoader)
# ═══════════════════════════════════════════════════════════════

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
from pathlib import Path

# Eksik kalan ImageNet normalizasyon değerleri:
CONFIG["mean"] = [0.485, 0.456, 0.406]
CONFIG["std"] = [0.229, 0.224, 0.225]

class EyeDeepfakeDataset(Dataset):
    def __init__(self, root_dir, split="train", transform=None):
        self.root_dir = Path(root_dir) / split
        self.transform = transform
        self.images = []
        self.labels = []

        # 0 = Real, 1 = Fake
        for label_idx, label_name in enumerate(["real", "fake"]):
            folder = self.root_dir / label_name
            if not folder.exists(): continue

            for img_path in folder.glob("*.jpg"):
                self.images.append(str(img_path))
                self.labels.append(label_idx)

        print(f"📁 {split.upper()} Seti Yüklendi -> Toplam: {len(self.images)} Göz (Real: {self.labels.count(0)}, Fake: {self.labels.count(1)})")

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        label = self.labels[idx]

        # Resmi aç ve RGB'ye çevir
        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, torch.tensor(label, dtype=torch.long)

# 1. Transformasyonlar (Fotoğrafları sayıya çevirme ve standartlaştırma)
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((CONFIG["image_size"], CONFIG["image_size"])),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.ColorJitter(brightness=0.1, contrast=0.1),
        transforms.ToTensor(),
        transforms.Normalize(CONFIG["mean"], CONFIG["std"])
    ]),
    'val': transforms.Compose([
        transforms.Resize((CONFIG["image_size"], CONFIG["image_size"])),
        transforms.ToTensor(),
        transforms.Normalize(CONFIG["mean"], CONFIG["std"])
    ]),
    'test': transforms.Compose([
        transforms.Resize((CONFIG["image_size"], CONFIG["image_size"])),
        transforms.ToTensor(),
        transforms.Normalize(CONFIG["mean"], CONFIG["std"])
    ]),
}

# 2. Datasetleri Oluştur
print("⏳ Veri setleri (Tensörler) hazırlanıyor...")
datasets = {
    x: EyeDeepfakeDataset(CONFIG["eye_dir"], split=x, transform=data_transforms[x])
    for x in ['train', 'val', 'test']
}

# 3. DataLoader'ları Oluştur (32'li paketler halinde CPU'dan GPU'ya taşır)
dataloaders = {
    x: DataLoader(datasets[x], batch_size=CONFIG["batch_size"], shuffle=(x == 'train'), num_workers=2)
    for x in ['train', 'val', 'test']
}

dataset_sizes = {x: len(datasets[x]) for x in ['train', 'val', 'test']}
class_names = ['real', 'fake']

print("\n✅ DATALOADER HAZIR!")
print(f"📦 Batch Size (Paket Boyutu): {CONFIG['batch_size']}")

# ═══════════════════════════════════════════════════════════════
# 🧠 MODEL EĞİTİMİ (Transfer Learning)
# ═══════════════════════════════════════════════════════════════

import copy
import time
from tqdm.notebook import tqdm
import torch.nn.functional as F

# 1. Modeli Seç ve Hazırla
model_name = CONFIG["current_model"]
print(f"🚀 {model_name.upper()} Modeli Yükleniyor...")

# 'timm' kütüphanesi ile ImageNet'te eğitilmiş modeli indir
# num_classes=2 (Real ve Fake)
model = timm.create_model(model_name, pretrained=True, num_classes=2)
model = model.to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=CONFIG["learning_rate"])

# 2. Eğitim Fonksiyonu
def train_model(model, criterion, optimizer, num_epochs=10):
    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_auc = 0.0
    history = {'train_loss': [], 'val_loss': [], 'train_auc': [], 'val_auc': []}

    for epoch in range(num_epochs):
        print(f"\n🔄 Epoch {epoch+1}/{num_epochs}")
        print("-" * 30)

        for phase in ['train', 'val']:
            if phase == 'train':
                model.train()  # Modeli eğitim moduna al
            else:
                model.eval()   # Modeli test moduna al (ağırlıkları kilitle)

            running_loss = 0.0
            all_preds = []
            all_labels = []

            # Progress bar (tqdm)
            for inputs, labels in tqdm(dataloaders[phase], desc=phase.upper(), leave=False):
                inputs = inputs.to(DEVICE)
                labels = labels.to(DEVICE)

                optimizer.zero_grad() # Önceki adımdan kalan hataları sıfırla

                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    loss = criterion(outputs, labels)

                    # Softmax ile çıktıları olasılıklara (0.0 - 1.0) çevir
                    probs = F.softmax(outputs, dim=1)[:, 1]

                    if phase == 'train':
                        loss.backward()  # Geri yayılım (Öğrenme)
                        optimizer.step()

                running_loss += loss.item() * inputs.size(0)
                all_preds.extend(probs.cpu().detach().numpy())
                all_labels.extend(labels.cpu().numpy())

            # Tur (Epoch) Sonu Hesaplamaları
            epoch_loss = running_loss / dataset_sizes[phase]
            # Dengesiz veri setleri için Accuracy yerine ROC_AUC daha güvenilirdir
            epoch_auc = roc_auc_score(all_labels, all_preds)

            history[f'{phase}_loss'].append(epoch_loss)
            history[f'{phase}_auc'].append(epoch_auc)

            print(f"📊 {phase.upper()} -> Loss: {epoch_loss:.4f} | AUC: {epoch_auc:.4f}")

            # Eğer validation AUC skoru şimdiye kadarkinden iyiyse, modeli kaydet!
            if phase == 'val' and epoch_auc > best_auc:
                print(f"⭐ YENİ REKOR! (AUC: {best_auc:.4f} -> {epoch_auc:.4f}) Model Kaydediliyor...")
                best_auc = epoch_auc
                best_model_wts = copy.deepcopy(model.state_dict())

    time_elapsed = time.time() - since
    print(f"\n✅ EĞİTİM TAMAMLANDI! (Süre: {time_elapsed // 60:.0f}dk {time_elapsed % 60:.0f}sn)")
    print(f"🏆 En İyi Val AUC Skoru: {best_auc:.4f}")

    # En iyi öğrenmiş haliyle modeli geri döndür
    model.load_state_dict(best_model_wts)

    # En iyi modeli diske kaydet
    save_path = f"{CONFIG['results_dir']}/best_{model_name}.pth"
    torch.save(model.state_dict(), save_path)
    print(f"💾 Model diske kaydedildi: {save_path}")

    return model, history

# 3. Eğitimi Başlat
model, history = train_model(model, criterion, optimizer, num_epochs=CONFIG["epochs"])

# ═══════════════════════════════════════════════════════════════
# 📈 TEST SETİ DEĞERLENDİRMESİ VE GRAFİKLER
# ═══════════════════════════════════════════════════════════════

import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, average_precision_score, confusion_matrix,
    roc_curve, precision_recall_curve
)
import torch.nn.functional as F

model_name = CONFIG["current_model"]
print(f"🔍 {model_name.upper()} Modeli Test Setinde Sınava Sokuluyor...")

# 1. En iyi modeli disktan yükle
model.load_state_dict(torch.load(f"{CONFIG['results_dir']}/best_{model_name}.pth"))
model.eval()

all_preds_probs = []
all_preds_classes = []
all_labels = []

# 2. Test Verisi Üzerinde Tahmin Yap
with torch.no_grad():
    for inputs, labels in dataloaders['test']:
        inputs = inputs.to(DEVICE)
        labels = labels.to(DEVICE)

        outputs = model(inputs)
        probs = F.softmax(outputs, dim=1)[:, 1] # Fake olma olasılığı
        preds = torch.argmax(outputs, dim=1)    # 0 veya 1 tahmini

        all_preds_probs.extend(probs.cpu().numpy())
        all_preds_classes.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# 3. Metrikleri Hesapla
acc = accuracy_score(all_labels, all_preds_classes)
prec = precision_score(all_labels, all_preds_classes)
rec = recall_score(all_labels, all_preds_classes)
f1 = f1_score(all_labels, all_preds_classes)
auc = roc_auc_score(all_labels, all_preds_probs)
pr_auc = average_precision_score(all_labels, all_preds_probs)

# Specificity (Gerçekleri Doğru Bilme Oranı)
tn, fp, fn, tp = confusion_matrix(all_labels, all_preds_classes).ravel()
specificity = tn / (tn + fp)

print("\n" + "="*40)
print(f"🏆 {model_name.upper()} - TEST SETİ SONUÇLARI")
print("="*40)
print(f"Accuracy    : {acc:.4f}")
print(f"Precision   : {prec:.4f}")
print(f"Recall      : {rec:.4f}")
print(f"Specificity : {specificity:.4f}  <-- (ÖNEMLİ: Gerçekleri ayırt etme)")
print(f"F1-Score    : {f1:.4f}")
print(f"ROC-AUC     : {auc:.4f}")
print(f"PR-AUC      : {pr_auc:.4f}")
print("="*40)

# 4. GRAFİKLERİ ÇİZ
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle(f"{model_name.upper()} - Değerlendirme Grafikleri", fontsize=16, fontweight='bold')

# Grafik A: Confusion Matrix
cm = confusion_matrix(all_labels, all_preds_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Real (0)', 'Fake (1)'],
            yticklabels=['Real (0)', 'Fake (1)'])
axes[0].set_title("Karmaşıklık Matrisi (Confusion Matrix)")
axes[0].set_ylabel('Gerçek Değerler')
axes[0].set_xlabel('Tahmin Edilen Değerler')

# Grafik B: ROC Curve
fpr, tpr, _ = roc_curve(all_labels, all_preds_probs)
axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC (AUC = {auc:.3f})')
axes[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axes[1].set_title('ROC Eğrisi')
axes[1].set_xlabel('False Positive Oranı')
axes[1].set_ylabel('True Positive Oranı')
axes[1].legend(loc="lower right")

# Grafik C: Eğitim Geçmişi (Eğitim sırasındaki Loss değişimi)
axes[2].plot(history['train_loss'], label='Train Loss')
axes[2].plot(history['val_loss'], label='Val Loss')
axes[2].set_title('Eğitim Sürecinde Hata (Loss) Eğrisi')
axes[2].set_xlabel('Tur (Epoch)')
axes[2].set_ylabel('Hata Değeri (Loss)')
axes[2].legend()

plt.tight_layout()
plt.savefig(f"{CONFIG['reports_dir']}/{model_name}_evaluation.pdf", dpi=300)
print(f"\n📁 Grafikler PDF olarak kaydedildi: {CONFIG['reports_dir']}/{model_name}_evaluation.pdf")
plt.show()

# ═══════════════════════════════════════════════════════════════
# 🔬 AÇIKLANABİLİR YAPAY ZEKA (Grad-CAM)
# ═══════════════════════════════════════════════════════════════

!pip install -q grad-cam

import cv2
import numpy as np
import matplotlib.pyplot as plt
import torch
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

model.eval()

# Modele göre Grad-CAM'in bakacağı son evrişim (convolution) katmanını seçiyoruz
target_layers = []
if "resnet" in model_name:
    target_layers = [model.layer4[-1]]
elif "efficientnet" in model_name:
    target_layers = [model.conv_head]
elif "densenet" in model_name:
    target_layers = [model.features.norm5]
elif "mobilenet" in model_name:
    target_layers = [model.blocks[-1]]
elif "xception" in model_name:
    target_layers = [model.act4]
else:
    print("Bilinmeyen model katmanı!")

cam = GradCAM(model=model, target_layers=target_layers)

# Test setinden rastgele 1 batch (32 fotoğraf) al
inputs, labels = next(iter(dataloaders['test']))
inputs = inputs.to(DEVICE)
labels = labels.to(DEVICE)

# Tahminleri yap
outputs = model(inputs)
preds = torch.argmax(outputs, dim=1)

# Ekrana 4 tane örnek çizdirelim (2 Real, 2 Fake)
fig, axes = plt.subplots(2, 4, figsize=(16, 8))
fig.suptitle(f"{model_name.upper()} - Nereye Bakarak Karar Veriyor? (Grad-CAM)", fontsize=16, fontweight='bold')

plot_idx = 0
for i in range(len(inputs)):
    if plot_idx >= 8: break # Sadece 8 tane çiz

    input_tensor = inputs[i].unsqueeze(0)
    actual_label = "Fake" if labels[i] == 1 else "Real"
    pred_label = "Fake" if preds[i] == 1 else "Real"

    # 1. Grad-CAM Maskesini Oluştur
    target = [ClassifierOutputTarget(preds[i].item())]
    grayscale_cam = cam(input_tensor=input_tensor, targets=target)[0, :]

    # 2. Orijinal Görüntüyü Geri Çevir (Normalizasyonu Geri Al)
    img_tensor = inputs[i].cpu().numpy().transpose((1, 2, 0))
    mean = np.array(CONFIG["mean"])
    std = np.array(CONFIG["std"])
    img_original = std * img_tensor + mean
    img_original = np.clip(img_original, 0, 1)

    # 3. Isı Haritasını Görüntü Üstüne Koy
    visualization = show_cam_on_image(img_original, grayscale_cam, use_rgb=True)

    # Orijinal vs GradCAM Çizimi
    row = plot_idx // 4
    col = plot_idx % 4

    axes[row, col].imshow(visualization)

    # Eğer doğru bildiyse YEŞİL, yanlış bildiyse KIRMIZI başlık
    color = "green" if actual_label == pred_label else "red"
    axes[row, col].set_title(f"Gerçek: {actual_label} | Tahmin: {pred_label}", color=color)
    axes[row, col].axis('off')

    plot_idx += 1

plt.tight_layout()
plt.savefig(f"{CONFIG['reports_dir']}/{model_name}_gradcam.pdf", dpi=300)
print(f"📁 Isı haritaları PDF olarak kaydedildi: {CONFIG['reports_dir']}/{model_name}_gradcam.pdf")
plt.show()

CONFIG["current_model"] = "efficientnet_b0"
print("✅ Hedef Model Değiştirildi:", CONFIG["current_model"])

CONFIG["current_model"] = "densenet121"
print("✅ Hedef Model Değiştirildi:", CONFIG["current_model"])

CONFIG["current_model"] = "mobilenetv3_small_100"
print("✅ Hedef Model Düzeltildi:", CONFIG["current_model"])

CONFIG["current_model"] = "xception"
print("✅ Hedef Model Değiştirildi:", CONFIG["current_model"])