# -*- coding: utf-8 -*-
"""framecikarma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEd76E075xSZwglcQps4tzN5RmYXxt2D
"""

from google.colab import drive
drive.mount("/content/drive")

import os
for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "fake" in dirs or "FaceForensics_Projesi" in dirs:
        print(root)

import os
print(os.listdir("/content/drive/MyDrive"))

import os
print(os.listdir("/content/drive/MyDrive/AISC DeepFake Çalışmaları"))

import os
print(os.listdir("/content/drive/MyDrive/AISC DeepFake Çalışmaları/FaceForensics_Projesi"))

!pip install opencv-python



"""
FAKE videolar için frame çıkarma
- Girdi yapısı:
  fake/
    train/*.mp4
    val/*.mp4
    test/*.mp4

- Çıktı yapısı:
  fake_frames/
    train/<video_adi>/frame_000000.jpg
    val/<video_adi>/frame_000000.jpg
    test/<video_adi>/frame_000000.jpg

Bu kod videoları yeniden bölmez.
Mevcut train / val / test klasörlerinin içindeki videolardan
0.7 saniyede bir frame çıkarır.

Google Colab'da önce:
from google.colab import drive
drive.mount("/content/drive")
"""

from pathlib import Path
import cv2

# ===================== AYARLAR =====================
INPUT_ROOT = Path(
    "/content/drive/MyDrive/AISC DeepFake Çalışmaları/FaceForensics_Projesi/fake"
)
OUTPUT_ROOT = Path(
    "/content/drive/MyDrive/AISC DeepFake Çalışmaları/FaceForensics_Projesi/fake_frames"
)

INTERVAL_SECONDS = 0.7
IMAGE_EXTENSION = ".jpg"
JPEG_QUALITY = 95
OVERWRITE = False

VIDEO_EXTENSIONS = {
    ".mp4", ".avi", ".mov", ".mkv", ".webm", ".m4v"
}

SPLITS = ("train", "val", "test")
# ==================================================


def find_videos(folder: Path) -> list[Path]:
    """Klasör ve alt klasörlerindeki video dosyalarını bulur."""
    return sorted(
        path
        for path in folder.rglob("*")
        if path.is_file()
        and path.suffix.lower() in VIDEO_EXTENSIONS
    )


def extract_frames(
    video_path: Path,
    output_dir: Path
) -> tuple[int, str]:
    """
    Videodan 0.0, 0.7, 1.4, 2.1... saniyelerde frame çıkarır.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    existing_frames = list(
        output_dir.glob(f"*{IMAGE_EXTENSION}")
    )

    if existing_frames and not OVERWRITE:
        return 0, "atlandı (çıktı zaten var)"

    capture = cv2.VideoCapture(str(video_path))

    if not capture.isOpened():
        return 0, "HATA: video açılamadı"

    fps = capture.get(cv2.CAP_PROP_FPS)

    if fps <= 0:
        capture.release()
        return 0, "HATA: FPS okunamadı"

    frame_index = 0
    saved_count = 0
    next_sample_time = 0.0

    while True:
        success, frame = capture.read()

        if not success:
            break

        current_time = frame_index / fps

        # En yakın gerçek video karesini seçer.
        if current_time + (0.5 / fps) >= next_sample_time:
            output_file = (
                output_dir
                / f"frame_{saved_count:06d}{IMAGE_EXTENSION}"
            )

            write_ok = cv2.imwrite(
                str(output_file),
                frame,
                [
                    cv2.IMWRITE_JPEG_QUALITY,
                    JPEG_QUALITY
                ],
            )

            if not write_ok:
                capture.release()
                return (
                    saved_count,
                    f"HATA: {output_file.name} yazılamadı"
                )

            saved_count += 1
            next_sample_time += INTERVAL_SECONDS

        frame_index += 1

    capture.release()

    return saved_count, "tamamlandı"


def main() -> None:
    if not INPUT_ROOT.exists():
        raise FileNotFoundError(
            f"Girdi klasörü bulunamadı: {INPUT_ROOT}"
        )

    total_videos = 0
    total_frames = 0

    for split in SPLITS:
        split_input = INPUT_ROOT / split
        split_output = OUTPUT_ROOT / split

        if not split_input.exists():
            print(
                f"[UYARI] Klasör bulunamadı, geçildi: "
                f"{split_input}"
            )
            continue

        videos = find_videos(split_input)

        print(
            f"\n[{split.upper()}] "
            f"{len(videos)} video bulundu."
        )

        for number, video_path in enumerate(
            videos,
            start=1
        ):
            relative_path = video_path.relative_to(
                split_input
            )

            # Aynı isimli videolar alt klasörlerdeyse
            # çıktı çakışmasını önler.
            video_output = (
                split_output
                / relative_path.parent
                / video_path.stem
            )

            frame_count, status = extract_frames(
                video_path,
                video_output
            )

            total_videos += 1
            total_frames += frame_count

            print(
                f"[{number}/{len(videos)}] "
                f"{relative_path} -> "
                f"{frame_count} frame | {status}"
            )

    print("\nİŞLEM BİTTİ")
    print(f"İşlenen video: {total_videos}")
    print(
        f"Yeni çıkarılan frame: {total_frames}"
    )
    print(f"Çıktı klasörü: {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()